<?php
$cats = array(
'Abyssinian Cat',
'American Bobtail',
'American Curl',
'American Shorthair',
'American Wirehair',
'Balinese cat',
'Bengal',
'Birman',
'Bombay',
'British Longhair',
'British Shorthair',
'Burmese',
'Burmilla',
'California Spangled',
'Californian Rex',
'Ceylon',
'Chartreux',
'Chausie',
'Chinchilla Persian',
'Cornish Rex',
'Cymric',
'Devon Rex',
'Domestic cat (Moggy)',
'Donskoy',
'Egyptian Mau',
'European Shorthair',
'Exotic shorthair',
'German Rex',
'Havana Brown',
'Highland Fold',
'Himalayen',
'Japanese Bobtail',
'Javanese',
'Khao Manee',
'Korat',
'LaPerm',
'Maine Coon',
'Manx',
'Munchkin',
'Nebelung',
'Norwegian Forest cat',
'Ocicat',
'Oriental',
'Persian',
'Peterbald',
'Pixie-bob',
'Ragamuffin',
'Ragdoll',
'Russian Blue',
'Safari',
'Savannah',
'Scottish Fold',
'Selkirk Rex',
'Siamese Cat',
'Siberian cat',
'Singapura',
'Snowshoe',
'Sokoke',
'Somali',
'Sphynx',
'Thaï',
'Tiffany',
'Tonkinese',
'Toyger',
'Turkish Angora',
'Turkish Van',
'York Chocolate',
);

// catsArray isaugojimas i JSON faila

$json = json_encode(array('data' => $cats));

if (file_put_contents("data.json", $json))
    echo "JSON file created successfully...";
else 
    echo "Oops! Error creating json file...";

?>